### ISSUE TITLE
pretrained .pth model file load error.

### ISSUE THREAD

**Issue by boostlee** [kevinlu1211/deep-photo-aesthetics#1]
"RuntimeError: unexpected EOF. The file might be corrupted. " for line:
net.load_state_dict(torch.load(os.path.join(save_path, checkpoint)))
Is the .pth file completed? Thanks a lot.

**Comment by kevinlu1211** [comment]
It should be completed, but if it isn't try retraining from scratch as it shouldn't take that long!

**Comment by boostlee** [comment]
OK, I will try to retrain the model, thanks for help.

**Comment by ViswanathaReddyGajjala** [comment]
hey @boostlee can you send the retrained model to my mail(viswanatha.g15@iiits.in).
