### ISSUE TITLE
RuntimeError: Given groups=1, weight[512, 2048, 1, 1], so expected input[16, 64, 75, 75] to have 2048 channels, but got 64 channels instead

### ISSUE THREAD

**Issue by boostlee** [kevinlu1211/deep-photo-aesthetics#2]
When I run the training program, I got the following runtime error:
RuntimeError: Given groups=1, weight[512, 2048, 1, 1], so expected input[16, 64, 75, 75] to have 2048 channels, but got 64 channels instead
@kevinlu1211 , can you help me, thanks a lot.

**Comment by kevinlu1211** [comment]
Without knowing your input I don’t know how to help, but the error is
pretty clear the channels aren’t matching up so step through it with a
debugger to figure it out.

**Comment by boostlee** [comment]
I have found the problem.  In resnet_FT.py, codes like "self.model.add_module("bn_{count}", bn)" do not run as expected, in my environment, the "count" not replaced by the runtime value. After changing to "self.model.add_module("bn_{}".format(count), bn)", the code running well.
