### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by musdfakoc** [kevinlu1211/deep-photo-aesthetics#9]
Hi, great work there. I did try the pertained model but it gave an error as 
RuntimeError: unexpected EOF. The file might be corrupted.

So I did train the model from scratch and did try new file in the notebook, it gave an error as
UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.

What should I do,  I am bit confused. Thanks already.

**Comment by kevin-skand-io** [comment]
Hi, maybe you could try upgrading the version of torch? The version in this repo was from 3 years ago

**Comment by musdfakoc** [comment]
It worked when I updated the pytorch yet still it does not work with your checkpoint data, it works with newly trained checkpoint.
